# Generated by Django 3.2.6 on 2021-08-03 08:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
