# Generated by Django 3.2.6 on 2021-08-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_tour_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='khachhang',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='employee',
            name='CMND',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='CMND',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
